// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package metric

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric(in *jlexer.Lexer, out *MetricsForDay) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SlotID = string(in.String())
			}
		case "clicks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Clicks = int32(in.Int32())
			}
		case "impressions":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Impressions = int32(in.Int32())
			}
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric(out *jwriter.Writer, in MetricsForDay) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"slot_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SlotID))
	}
	{
		const prefix string = ",\"clicks\":"
		out.RawString(prefix)
		out.Int32(int32(in.Clicks))
	}
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix)
		out.Int32(int32(in.Impressions))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.EventDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MetricsForDay) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MetricsForDay) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MetricsForDay) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MetricsForDay) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric(l, v)
}
func easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric1(in *jlexer.Lexer, out *Metric) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SlotID":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.SlotID[:], in.Bytes())
			}
		case "AdDetailID":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.AdDetailID[:], in.Bytes())
			}
		case "EventType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventType = string(in.String())
			}
		case "CreateeTime":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreateeTime).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric1(out *jwriter.Writer, in Metric) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SlotID\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.SlotID[:])
	}
	{
		const prefix string = ",\"AdDetailID\":"
		out.RawString(prefix)
		out.Base64Bytes(in.AdDetailID[:])
	}
	{
		const prefix string = ",\"EventType\":"
		out.RawString(prefix)
		out.String(string(in.EventType))
	}
	{
		const prefix string = ",\"CreateeTime\":"
		out.RawString(prefix)
		out.Raw((in.CreateeTime).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metric) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metric) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metric) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metric) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric1(l, v)
}
func easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric2(in *jlexer.Lexer, out *GetMetricsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SlotID = string(in.String())
			}
		case "total_clicks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalClicks = int32(in.Int32())
			}
		case "total_impressions":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalImpressions = int32(in.Int32())
			}
		case "daily_stats":
			if in.IsNull() {
				in.Skip()
				out.Metrics = nil
			} else {
				in.Delim('[')
				if out.Metrics == nil {
					if !in.IsDelim(']') {
						out.Metrics = make([]MetricsForDay, 0, 1)
					} else {
						out.Metrics = []MetricsForDay{}
					}
				} else {
					out.Metrics = (out.Metrics)[:0]
				}
				for !in.IsDelim(']') {
					var v5 MetricsForDay
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Metrics = append(out.Metrics, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric2(out *jwriter.Writer, in GetMetricsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"slot_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SlotID))
	}
	{
		const prefix string = ",\"total_clicks\":"
		out.RawString(prefix)
		out.Int32(int32(in.TotalClicks))
	}
	{
		const prefix string = ",\"total_impressions\":"
		out.RawString(prefix)
		out.Int32(int32(in.TotalImpressions))
	}
	{
		const prefix string = ",\"daily_stats\":"
		out.RawString(prefix)
		if in.Metrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Metrics {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMetricsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMetricsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMetricsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMetricsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric2(l, v)
}
func easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric3(in *jlexer.Lexer, out *GetMetric) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SlotID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SlotID = string(in.String())
			}
		case "EventDate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EventDate).UnmarshalJSON(data))
				}
			}
		case "Impressions":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Impressions = int(in.Int())
			}
		case "Clicks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Clicks = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric3(out *jwriter.Writer, in GetMetric) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SlotID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SlotID))
	}
	{
		const prefix string = ",\"EventDate\":"
		out.RawString(prefix)
		out.Raw((in.EventDate).MarshalJSON())
	}
	{
		const prefix string = ",\"Impressions\":"
		out.RawString(prefix)
		out.Int(int(in.Impressions))
	}
	{
		const prefix string = ",\"Clicks\":"
		out.RawString(prefix)
		out.Int(int(in.Clicks))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMetric) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMetric) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20252404InternalServiceSlotDomainMetric3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMetric) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMetric) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20252404InternalServiceSlotDomainMetric3(l, v)
}
