// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: profile/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Company       string                 `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	AdsCount      uint32                 `protobuf:"varint,9,opt,name=ads_count,json=adsCount,proto3" json:"ads_count,omitempty"`
	ProfileType   string                 `protobuf:"bytes,10,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRequest) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *UpdateRequest) GetAdsCount() uint32 {
	if x != nil {
		return x.AdsCount
	}
	return 0
}

func (x *UpdateRequest) GetProfileType() string {
	if x != nil {
		return x.ProfileType
	}
	return ""
}

func (x *UpdateRequest) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	FirstSubname  string                 `protobuf:"bytes,5,opt,name=first_subname,json=firstSubname,proto3" json:"first_subname,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	AdsCount      uint32                 `protobuf:"varint,9,opt,name=ads_count,json=adsCount,proto3" json:"ads_count,omitempty"`
	ProfileType   string                 `protobuf:"bytes,10,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"`
	Company       string                 `protobuf:"bytes,11,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateResponse) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UpdateResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateResponse) GetFirstSubname() string {
	if x != nil {
		return x.FirstSubname
	}
	return ""
}

func (x *UpdateResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *UpdateResponse) GetAdsCount() uint32 {
	if x != nil {
		return x.AdsCount
	}
	return 0
}

func (x *UpdateResponse) GetProfileType() string {
	if x != nil {
		return x.ProfileType
	}
	return ""
}

func (x *UpdateResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{2}
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{3}
}

type ShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowRequest) Reset() {
	*x = ShowRequest{}
	mi := &file_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRequest) ProtoMessage() {}

func (x *ShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRequest.ProtoReflect.Descriptor instead.
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{4}
}

type ShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Company       string                 `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	AdsCount      uint32                 `protobuf:"varint,9,opt,name=ads_count,json=adsCount,proto3" json:"ads_count,omitempty"`
	ProfileType   string                 `protobuf:"bytes,10,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	mi := &file_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ShowResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ShowResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShowResponse) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *ShowResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ShowResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ShowResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *ShowResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ShowResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *ShowResponse) GetAdsCount() uint32 {
	if x != nil {
		return x.AdsCount
	}
	return 0
}

func (x *ShowResponse) GetProfileType() string {
	if x != nil {
		return x.ProfileType
	}
	return ""
}

var File_profile_profile_proto protoreflect.FileDescriptor

const file_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x15profile/profile.proto\x12\aprofile\"\xc7\x02\n" +
	"\rUpdateRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x18\n" +
	"\acompany\x18\x06 \x01(\tR\acompany\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12#\n" +
	"\rregistered_at\x18\b \x01(\tR\fregisteredAt\x12\x1b\n" +
	"\tads_count\x18\t \x01(\rR\badsCount\x12!\n" +
	"\fprofile_type\x18\n" +
	" \x01(\tR\vprofileType\x12\x16\n" +
	"\x06avatar\x18\v \x01(\fR\x06avatar\"\xd1\x02\n" +
	"\x0eUpdateResponse\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\fR\x06avatar\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12#\n" +
	"\rfirst_subname\x18\x05 \x01(\tR\ffirstSubname\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12#\n" +
	"\rregistered_at\x18\b \x01(\tR\fregisteredAt\x12\x1b\n" +
	"\tads_count\x18\t \x01(\rR\badsCount\x12!\n" +
	"\fprofile_type\x18\n" +
	" \x01(\tR\vprofileType\x12\x18\n" +
	"\acompany\x18\v \x01(\tR\acompany\"\x0f\n" +
	"\rDeleteRequest\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vShowRequest\"\xaa\x02\n" +
	"\fShowResponse\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\fR\x06avatar\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x18\n" +
	"\acompany\x18\x06 \x01(\tR\acompany\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12#\n" +
	"\rregistered_at\x18\b \x01(\tR\fregisteredAt\x12\x1b\n" +
	"\tads_count\x18\t \x01(\rR\badsCount\x12!\n" +
	"\fprofile_type\x18\n" +
	" \x01(\tR\vprofileType2\xb4\x01\n" +
	"\aProfile\x129\n" +
	"\x06Update\x12\x16.profile.UpdateRequest\x1a\x17.profile.UpdateResponse\x129\n" +
	"\x06Delete\x12\x16.profile.DeleteRequest\x1a\x17.profile.DeleteResponse\x123\n" +
	"\x04Show\x12\x14.profile.ShowRequest\x1a\x15.profile.ShowResponseB\x13Z\x11./protos/profile;b\x06proto3"

var (
	file_profile_profile_proto_rawDescOnce sync.Once
	file_profile_profile_proto_rawDescData []byte
)

func file_profile_profile_proto_rawDescGZIP() []byte {
	file_profile_profile_proto_rawDescOnce.Do(func() {
		file_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)))
	})
	return file_profile_profile_proto_rawDescData
}

var file_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_profile_profile_proto_goTypes = []any{
	(*UpdateRequest)(nil),  // 0: profile.UpdateRequest
	(*UpdateResponse)(nil), // 1: profile.UpdateResponse
	(*DeleteRequest)(nil),  // 2: profile.DeleteRequest
	(*DeleteResponse)(nil), // 3: profile.DeleteResponse
	(*ShowRequest)(nil),    // 4: profile.ShowRequest
	(*ShowResponse)(nil),   // 5: profile.ShowResponse
}
var file_profile_profile_proto_depIdxs = []int32{
	0, // 0: profile.Profile.Update:input_type -> profile.UpdateRequest
	2, // 1: profile.Profile.Delete:input_type -> profile.DeleteRequest
	4, // 2: profile.Profile.Show:input_type -> profile.ShowRequest
	1, // 3: profile.Profile.Update:output_type -> profile.UpdateResponse
	3, // 4: profile.Profile.Delete:output_type -> profile.DeleteResponse
	5, // 5: profile.Profile.Show:output_type -> profile.ShowResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_profile_proto_init() }
func file_profile_profile_proto_init() {
	if File_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_profile_proto_goTypes,
		DependencyIndexes: file_profile_profile_proto_depIdxs,
		MessageInfos:      file_profile_profile_proto_msgTypes,
	}.Build()
	File_profile_profile_proto = out.File
	file_profile_profile_proto_goTypes = nil
	file_profile_profile_proto_depIdxs = nil
}
