// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ad

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecode20252404InternalServiceAdDomainAd(in *jlexer.Lexer, out *Ads) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "add_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "ClientID":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ClientID).UnmarshalText(data))
				}
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "budget":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Budget = uint32(in.Uint32())
			}
		case "img_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImagePath = string(in.String())
			}
		case "target_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetURL = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20252404InternalServiceAdDomainAd(out *jwriter.Writer, in Ads) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"add_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"ClientID\":"
		out.RawString(prefix)
		out.RawText((in.ClientID).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"budget\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Budget))
	}
	{
		const prefix string = ",\"img_path\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"target_url\":"
		out.RawString(prefix)
		out.String(string(in.TargetURL))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Ads) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20252404InternalServiceAdDomainAd(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Ads) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20252404InternalServiceAdDomainAd(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Ads) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20252404InternalServiceAdDomainAd(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Ads) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20252404InternalServiceAdDomainAd(l, v)
}
