CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	user_name VARCHAR(255) NOT NULL
);

CREATE TABLE ads (
	id SERIAL PRIMARY KEY,
	creator_id INTEGER REFERENCES users(id),
	file_path VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	text TEXT NOT NULL
);

CREATE TABLE session (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id),
	session_id VARCHAR(255) UNIQUE NOT NULL
);