CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	user_name VARCHAR(30) NOT NULL
);

CREATE TABLE ads (
	id SERIAL PRIMARY KEY,
	creator_id INTEGER REFERENCES users(id),
	file_path VARCHAR(100) NOT NULL,
	title VARCHAR(30) NOT NULL,
	text TEXT NOT NULL
);

CREATE TABLE session (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id),
	session_id VARCHAR(100) UNIQUE NOT NULL
);