// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package user

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBed2650eDecode20252404InternalServiceProfileDomain(in *jlexer.Lexer, out *BalanceOp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "add_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddAmount = uint32(in.Uint32())
			}
		case "subtract_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubtractAmount = uint32(in.Uint32())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = uint32(in.Uint32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncode20252404InternalServiceProfileDomain(out *jwriter.Writer, in BalanceOp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"add_amount\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.AddAmount))
	}
	{
		const prefix string = ",\"subtract_amount\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SubtractAmount))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Balance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BalanceOp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncode20252404InternalServiceProfileDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BalanceOp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncode20252404InternalServiceProfileDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BalanceOp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecode20252404InternalServiceProfileDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BalanceOp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecode20252404InternalServiceProfileDomain(l, v)
}
