// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package user

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e1087fdDecode20252404InternalServiceProfileDomain(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "user_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "img_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImagePath = string(in.String())
			}
		case "user_first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserFirstName = string(in.String())
			}
		case "user_second_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserLastName = string(in.String())
			}
		case "company":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Company = string(in.String())
			}
		case "phone_number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "registred_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RegistrationDate = string(in.String())
			}
		case "ads_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdsCount = int(in.Int())
			}
		case "profile_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProfileType = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e1087fdEncode20252404InternalServiceProfileDomain(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"user_name\":"
		out.RawString(prefix)
		out.String(string(in.UserName))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"img_path\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"user_first_name\":"
		out.RawString(prefix)
		out.String(string(in.UserFirstName))
	}
	{
		const prefix string = ",\"user_second_name\":"
		out.RawString(prefix)
		out.String(string(in.UserLastName))
	}
	{
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		out.String(string(in.Company))
	}
	{
		const prefix string = ",\"phone_number\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"registred_at\":"
		out.RawString(prefix)
		out.String(string(in.RegistrationDate))
	}
	{
		const prefix string = ",\"ads_count\":"
		out.RawString(prefix)
		out.Int(int(in.AdsCount))
	}
	{
		const prefix string = ",\"profile_type\":"
		out.RawString(prefix)
		out.String(string(in.ProfileType))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v User) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e1087fdEncode20252404InternalServiceProfileDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e1087fdEncode20252404InternalServiceProfileDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *User) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e1087fdDecode20252404InternalServiceProfileDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e1087fdDecode20252404InternalServiceProfileDomain(l, v)
}
