// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package slot

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	template "html/template"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot(in *jlexer.Lexer, out *SlotRenderData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "ImageSrc":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImageSrc = string(in.String())
			}
		case "ImageData":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImageData = template.URL(in.String())
			}
		case "Link":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Link = string(in.String())
			}
		case "Background":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Background = string(in.String())
			}
		case "Color":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Color = string(in.String())
			}
		case "Banner":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Banner = string(in.String())
			}
		case "Slot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Slot = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot(out *jwriter.Writer, in SlotRenderData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"ImageSrc\":"
		out.RawString(prefix)
		out.String(string(in.ImageSrc))
	}
	{
		const prefix string = ",\"ImageData\":"
		out.RawString(prefix)
		out.String(string(in.ImageData))
	}
	{
		const prefix string = ",\"Link\":"
		out.RawString(prefix)
		out.String(string(in.Link))
	}
	{
		const prefix string = ",\"Background\":"
		out.RawString(prefix)
		out.String(string(in.Background))
	}
	{
		const prefix string = ",\"Color\":"
		out.RawString(prefix)
		out.String(string(in.Color))
	}
	{
		const prefix string = ",\"Banner\":"
		out.RawString(prefix)
		out.String(string(in.Banner))
	}
	{
		const prefix string = ",\"Slot\":"
		out.RawString(prefix)
		out.String(string(in.Slot))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SlotRenderData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SlotRenderData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SlotRenderData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SlotRenderData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot(l, v)
}
func easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot1(in *jlexer.Lexer, out *Slot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = ID(in.String())
			}
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = UserID(in.String())
			}
		case "SlotName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SlotName = string(in.String())
			}
		case "MinCostAdv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinCostAdv = int32(in.Int32())
			}
		case "FormatOfBanner":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FormatOfBanner = string(in.String())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "BackColor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BackColor = string(in.String())
			}
		case "TextColor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TextColor = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot1(out *jwriter.Writer, in Slot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"SlotName\":"
		out.RawString(prefix)
		out.String(string(in.SlotName))
	}
	{
		const prefix string = ",\"MinCostAdv\":"
		out.RawString(prefix)
		out.Int32(int32(in.MinCostAdv))
	}
	{
		const prefix string = ",\"FormatOfBanner\":"
		out.RawString(prefix)
		out.String(string(in.FormatOfBanner))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"BackColor\":"
		out.RawString(prefix)
		out.String(string(in.BackColor))
	}
	{
		const prefix string = ",\"TextColor\":"
		out.RawString(prefix)
		out.String(string(in.TextColor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Slot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Slot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD9cc51dcEncode20252404InternalServiceSlotDomainSlot1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Slot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Slot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD9cc51dcDecode20252404InternalServiceSlotDomainSlot1(l, v)
}
